### ISSUE TITLE
product_customer_code

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/product-attribute#1]

**Comment by andhit-r** [comment]
@mikevhe18 Analytic acc. nya **product_customer_code - Natura Aromatik**

**Comment by andhit-r** [comment]
Sudah dalam proses migrasi di https://github.com/OCA/product-attribute/pull/122

**Comment by andhit-r** [comment]
@mikevhe18 bantuin https://github.com/OCA/product-attribute/pull/122 yah. Lo pull dari branch https://github.com/hurrinico/product-attribute/tree/rebase_product_attribute. Kemudian:
- [ ] Kasih unittest supaya coveralsnya naik
- [ ] Sesuaian README.rst dengan template terbaru
- [ ] Ganti header pada tiap file .py dengan short header
- [ ] Masukin OpenSynergy Indonesia di daftar contributor di README.rst

**Comment by andhit-r** [comment]
Analytic Acc. tetep sama **product_customer_code - Natura Aromatik**

**Comment by mikevhe18** [comment]
PR to github hurricano [#1](https://github.com/hurrinico/product-attribute/pull/1)
